### ISSUE TITLE
multiple return types does not work

### ISSUE THREAD

**Issue by mchiasson** [vmanucharyan/duktape-cpp#11]
I tried the following:

```c++
#pragma once

#include "Element.h"

struct Document
{
    std::shared_ptr<Element> createElement(const char * tagName);

    template <class Inspector>
    static void inspect(Inspector &i) {
        i.construct(&std::make_shared<Document>);
        i.method("createElement", &Document::createElement);
    }

};

DUK_CPP_DEF_CLASS_NAME(Document);
```

where the implement returns different subclasses of the Element class:

```c++
std::shared_ptr<Element> Document::createElement(const char * tagName)
{
    if (strcmp(tagName, "canvas") == 0)
    {
        return std::make_shared<HTMLCanvasElement>();
    }

    if (strcmp(tagName, "image") == 0)
    {
        return std::make_shared<HTMLImageElement>();
    }

    if (strcmp(tagName, .......... 
    ...
    ...
    ...
}
```
However, because it returns the superclass `Element`, none of the functions and properties are visible in Javascript.

Is there a way to do this?

**Comment by vmanucharyan** [comment]
Do you mean functions and properties of subclasses?

You can only see functions and properties of `Element` class - that is intended.

If you want to downcast it you will probably need to implement downcasting methods inside Element class in your C++ code (e.g. `asHTMLImageElement()'). Or you can just call constructors directly.
