### ISSUE TITLE
have you an example on how to return a vector<char *> or an array ? 

### ISSUE THREAD

**Issue by peppemas** [vmanucharyan/duktape-cpp#14]

**Comment by vmanucharyan** [comment]
Raw pointers are not supported, there are 2 options:

- Use `std::vector<std::string>` assuming that your pointer actually points to string
- Wrap your `char*` into some structure and add custom type definition for it

Custom types:
https://github.com/vmanucharyan/duktape-cpp#custom-value-types

Couple of tests with `std::vector` as an example - may be useful too:
https://github.com/vmanucharyan/duktape-cpp/blob/master/tests/STLTypesTests.cpp#L56

**Comment by peppemas** [comment]
Hi @vmanucharyan,

Yes with vector<std::string> it works. 

Thank you!

**Comment by vmanucharyan** [comment]
glad I could help :)
